project:
  type: website

website:
  title: "STAT 251 Lab presentations"
  navbar:
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



